run:
	NEXT_PUBLIC_USER_SERVICE_URL=http://localhost:8081 \
	NEXT_PUBLIC_RATING_SERVICE_URL=http://localhost:8082 \
	NEXT_PUBLIC_MOVIE_SERVICE_URL=http://localhost:8083 \
	NEXT_PUBLIC_AUTH_SERVICE_URL=http://localhost:8084 \
	NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000 \
	npm run dev
