[movie_service]
environment = "development"
log_level = "debug"
    [movie_service.server]
    port = ":8083"
    read_timeout = 5 # seconds
    write_timeout = 5
    idle_timeout = 5

[mongodb]
uri = "mongodb://localhost:27019/moviedb"
db_name = "moviedb"
collection = "movies"
timeout = 4 # seconds
