basePath: /
definitions:
  domain.Claims:
    properties:
      aud:
        description: the `aud` (Audience) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3
        items:
          type: string
        type: array
      exp:
        allOf:
        - $ref: '#/definitions/domain.NumericDate'
        description: the `exp` (Expiration Time) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4
      iat:
        allOf:
        - $ref: '#/definitions/domain.NumericDate'
        description: the `iat` (Issued At) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6
      iss:
        type: string
      jti:
        description: the `jti` (JWT ID) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.7
        type: string
      level:
        $ref: '#/definitions/domain.Level'
      name:
        type: string
      nbf:
        allOf:
        - $ref: '#/definitions/domain.NumericDate'
        description: the `nbf` (Not Before) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.5
      sub:
        description: the `sub` (Subject) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2
        type: string
    type: object
  domain.FlowType:
    enum:
    - websiteSession
    - rememberMe
    type: string
    x-enum-varnames:
    - WebsiteSessionFlow
    - RememberMeFlow
  domain.Level:
    enum:
    - admin
    - user
    - anonymous
    type: string
    x-enum-varnames:
    - AdminLevel
    - UserLevel
    - AnonymousLevel
  domain.NumericDate:
    properties:
      time.Time:
        type: string
    type: object
  domain.Tokens:
    properties:
      accessToken:
        type: string
      accessTokenExpiration:
        type: integer
      refreshToken:
        type: string
      refreshTokenExpiration:
        type: integer
    type: object
  router.jwks:
    properties:
      keys:
        items:
          $ref: '#/definitions/router.key'
        type: array
    type: object
  router.key:
    properties:
      alg:
        type: string
      e:
        type: string
      kty:
        type: string
      "n":
        type: string
      use:
        type: string
    type: object
  router.loginPayload:
    properties:
      flow:
        $ref: '#/definitions/domain.FlowType'
      md5Password:
        type: string
      username:
        type: string
    type: object
  router.refreshPayload:
    properties:
      refreshToken:
        type: string
    type: object
  router.response:
    properties:
      error:
        type: string
      response: {}
      statusCode:
        type: integer
    type: object
  router.validationPayload:
    properties:
      accessToken:
        type: string
    type: object
host: localhost:8084
info:
  contact:
    name: Victor Springer
  description: Authentication Service for Movie Rating System.
  license:
    name: MIT License
  title: Authentication Service
  version: "1.0"
paths:
  /.well-known/jwks.json:
    get:
      consumes:
      - application/json
      description: Returns the JSON Web Key Set
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/router.response'
            - properties:
                response:
                  $ref: '#/definitions/router.jwks'
              type: object
      summary: JSON Web Key Set
      tags:
      - authentication
  /anonymous:
    post:
      consumes:
      - application/json
      description: Generates anonymous tokens for a new user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/router.response'
            - properties:
                response:
                  $ref: '#/definitions/domain.Tokens'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/router.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.response'
      summary: Login anonymously
      tags:
      - authentication
  /login:
    post:
      consumes:
      - application/json
      description: Generates tokens for an existing user
      parameters:
      - description: Login payload
        in: body
        name: loginPayload
        required: true
        schema:
          $ref: '#/definitions/router.loginPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/router.response'
            - properties:
                response:
                  $ref: '#/definitions/domain.Tokens'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/router.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/router.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.response'
      summary: Login
      tags:
      - authentication
  /logout:
    post:
      consumes:
      - application/json
      description: Revokes the access token
      parameters:
      - description: Authorization header with Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/router.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/router.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.response'
      summary: Logout
      tags:
      - authentication
  /refresh:
    post:
      consumes:
      - application/json
      description: Refreshes existing tokens
      parameters:
      - description: Refresh payload
        in: body
        name: refreshPayload
        required: true
        schema:
          $ref: '#/definitions/router.refreshPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/router.response'
            - properties:
                response:
                  $ref: '#/definitions/domain.Tokens'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/router.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/router.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.response'
      summary: Refresh tokens
      tags:
      - authentication
  /validate:
    post:
      consumes:
      - application/json
      description: Validates the provided access token
      parameters:
      - description: Validation payload
        in: body
        name: validationPayload
        required: true
        schema:
          $ref: '#/definitions/router.validationPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/router.response'
            - properties:
                response:
                  $ref: '#/definitions/domain.Claims'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/router.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/router.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.response'
      summary: Validate access token
      tags:
      - authentication
swagger: "2.0"
